"""
Django settings for Gauley project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from Gauley.ckeditorSetting import*
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)9=+0t_+9aj7u&3&03#94lbfo8a#_if^7akfivvf1%g4mfi0z='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.100.178", "10.0.2.2", "localhost", "127.0.0.1"]



# Application definition

INSTALLED_APPS = [
    
  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions','PaymentGateway',
    'django.contrib.messages','django_ckeditor_5',
    'django.contrib.staticfiles','MainApp','Authentication',
    'Blog','Invoice','Seller','Customer','RatingAndReview',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Gauley.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Authentication.context_processors.active_users_no',
                'MainApp.context_processors.product_filter_view',
                'PaymentGateway.context_processors.payment_details','PaymentGateway.context_processors.pay_customer_details',
                'Blog.context_processors.blog','RatingAndReview.context_processors.avg_rating',
                'RatingAndReview.context_processors.product_rating_context',
                
                
            ],
        },
    },
]

WSGI_APPLICATION = 'Gauley.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'gauley',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',  # Use the actual MySQL server host
#         'PORT': '3306',       # Default MySQL port
        
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL='media/'
MEDIA_ROOT=BASE_DIR / 'media'
LOGIN_URL = 'login'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'Authentication.User'

SITE_DOMAIN = 'http://127.0.0.1:8000'
SITE_NAME = 'GAULEY'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = 'live.smtp.mailtrap.io'
EMAIL_HOST_USER = 'api'
EMAIL_HOST_PASSWORD = 'f11fa56ae37d7a51a64639b8e4d6b8c3'
EMAIL_PORT = '587'
EMAIL_USE_TLS = True

# When user click on logout button below will be used to redirect user login page

LOGOUT_REDIRECT_URL = 'home'
# LOGIN_URL = 'login'
PASSWORD_RESET_TIMEOUT = 3600

#------------------------Esewa-paymentGateway----------------


ESEWA_BASE_URL = "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
ESEWA_SUCCESS_URL = "https://yourdomain.com/payment-success/"
ESEWA_FAILURE_URL = "https://yourdomain.com/payment-failure/"
ESEWA_SECRET_KEY = "8gBm/:&EnhH.1/q"  # For UAT, use the provided test key.

