# Generated by Django 4.2.19 on 2025-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentGateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('offline', 'Offline Payment')], max_length=20),
        ),
    ]
