# Generated by Django 4.2.19 on 2025-03-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentGateway', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
