# Generated by Django 4.2.19 on 2025-03-01 01:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(blank=True, max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country_code', models.CharField(choices=[('+977', '+977 | NP'), ('+91', '+91 | IN'), ('+86', '+86 | CN'), ('+1', '+1 | US'), ('+44', '+44 | GB'), ('+1', '+1 | CA'), ('+61', '+61 | AU'), ('+49', '+49 | DE'), ('+33', '+33 | FR'), ('+81', '+81 | JP'), ('+55', '+55 | BR'), ('+7', '+7 | RU'), ('+82', '+82 | KR'), ('+52', '+52 | MX'), ('+39', '+39 | IT'), ('+34', '+34 | ES'), ('+90', '+90 | TR'), ('+31', '+31 | NL'), ('+966', '+966 | SA'), ('+41', '+41 | CH'), ('+27', '+27 | ZA'), ('+54', '+54 | AR'), ('+46', '+46 | SE'), ('+234', '+234 | NG'), ('+48', '+48 | PL'), ('+47', '+47 | NO'), ('+62', '+62 | ID'), ('+84', '+84 | VN'), ('+66', '+66 | TH'), ('+63', '+63 | PH')], default='+977 ', max_length=5)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone number must be 10 digits')])),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Province 1', 'Province 1'), ('Madhesh Province', 'Madhesh Province'), ('Bagmati Province', 'Bagmati Province'), ('Gandaki Province', 'Gandaki Province'), ('Lumbini Province', 'Lumbini Province'), ('Karnali Province', 'Karnali Province'), ('Sudurpashchim Province', 'Sudurpashchim Province')], max_length=50)),
                ('district', models.CharField(choices=[('Bhojpur', 'Bhojpur'), ('Dhankuta', 'Dhankuta'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Khotang', 'Khotang'), ('Morang', 'Morang'), ('Okhaldhunga', 'Okhaldhunga'), ('Panchthar', 'Panchthar'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Solukhumbu', 'Solukhumbu'), ('Sunsari', 'Sunsari'), ('Taplejung', 'Taplejung'), ('Terhathum', 'Terhathum'), ('Udayapur', 'Udayapur'), ('Bara', 'Bara'), ('Dhanusha', 'Dhanusha'), ('Mahottari', 'Mahottari'), ('Parsa', 'Parsa'), ('Rautahat', 'Rautahat'), ('Saptari', 'Saptari'), ('Sarlahi', 'Sarlahi'), ('Siraha', 'Siraha'), ('Bhaktapur', 'Bhaktapur'), ('Chitwan', 'Chitwan'), ('Dhading', 'Dhading'), ('Dolakha', 'Dolakha'), ('Kathmandu', 'Kathmandu'), ('Kavrepalanchok', 'Kavrepalanchok'), ('Lalitpur', 'Lalitpur'), ('Makwanpur', 'Makwanpur'), ('Nuwakot', 'Nuwakot'), ('Ramechhap', 'Ramechhap'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Sindhupalchok', 'Sindhupalchok'), ('Baglung', 'Baglung'), ('Gorkha', 'Gorkha'), ('Kaski', 'Kaski'), ('Lamjung', 'Lamjung'), ('Manang', 'Manang'), ('Mustang', 'Mustang'), ('Myagdi', 'Myagdi'), ('Nawalpur', 'Nawalpur'), ('Parbat', 'Parbat'), ('Syangja', 'Syangja'), ('Tanahun', 'Tanahun'), ('Arghakhanchi', 'Arghakhanchi'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Dang', 'Dang'), ('Gulmi', 'Gulmi'), ('Kapilvastu', 'Kapilvastu'), ('Parasi', 'Parasi'), ('Palpa', 'Palpa'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum East', 'Rukum East'), ('Rupandehi', 'Rupandehi'), ('Dailekh', 'Dailekh'), ('Dolpa', 'Dolpa'), ('Humla', 'Humla'), ('Jajarkot', 'Jajarkot'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Mugu', 'Mugu'), ('Rukum West', 'Rukum West'), ('Salyan', 'Salyan'), ('Surkhet', 'Surkhet'), ('Achham', 'Achham'), ('Baitadi', 'Baitadi'), ('Bajhang', 'Bajhang'), ('Bajura', 'Bajura'), ('Dadeldhura', 'Dadeldhura'), ('Darchula', 'Darchula'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], max_length=100)),
                ('country', models.CharField(choices=[('Nepal', 'Nepal'), ('India', 'India'), ('China', 'China'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan'), ('Brazil', 'Brazil'), ('Russia', 'Russia'), ('South Korea', 'South Korea'), ('Mexico', 'Mexico'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Turkey', 'Turkey'), ('Netherlands', 'Netherlands'), ('Saudi Arabia', 'Saudi Arabia'), ('Switzerland', 'Switzerland'), ('South Africa', 'South Africa'), ('Argentina', 'Argentina'), ('Sweden', 'Sweden'), ('Nigeria', 'Nigeria'), ('Poland', 'Poland'), ('Norway', 'Norway'), ('Indonesia', 'Indonesia'), ('Vietnam', 'Vietnam'), ('Thailand', 'Thailand'), ('Philippines', 'Philippines')], default='Nepal', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(default='Gauley', max_length=100)),
                ('category', models.CharField(choices=[('Vegetables', 'Fresh Vegetables'), ('Fruits', 'Fresh Fruits'), ('DairyBakery', 'Dairy & Bakery Products'), ('Staples', 'Staples (Rice, Flour, Pulses, Grains)'), ('Proteins', 'Proteins (Eggs, Meat, Fish, Plant-based)'), ('HealthyFats', 'Healthy Fats & Oils (Ghee, Butter, Olive Oil)'), ('Beverages', 'Beverages (Tea, Coffee, Juices, Soft Drinks,Hard drinks)'), ('SpicesCondiments', 'Spices & Condiments'), ('HomemadeProducts', 'Homemade & Handcrafted Items'), ('LocalSpecialties', 'Local & Traditional Foods'), ('OrganicFoods', 'Organic & Natural Products'), ('PicklesJams', 'Pickles, Jams & Spreads'), ('HandmadeSnacks', 'Handmade Snacks & Sweets'), ('FermentedFoods', 'Fermented Foods (Yogurt, Kombucha, Kimchi)'), ('DryFruitsNuts', 'Dry Fruits, Seeds & Nuts'), ('FrozenFoods', 'Frozen Foods & Ready-to-Cook'), ('InstantFoods', 'Instant & Ready-to-Eat Foods'), ('BakeryConfectionery', 'Bakery, Cakes & Confectionery'), ('CerealsBreakfast', 'Cereals & Breakfast Foods'), ('Sweeteners', 'Sweeteners (Sugar, Jaggery, Honey)'), ('PackedFoods', 'Packed & Processed Foods'), ('SnacksNamkeen', 'Snacks, Namkeen & Chips'), ('CannedFoods', 'Canned & Preserved Foods'), ('SaucesSpreads', 'Sauces, Ketchup & Spreads'), ('NoodlesPasta', 'Noodles, Pasta & Instant Meals'), ('BiscuitsCookies', 'Biscuits, Cookies & Crackers'), ('ChocolatesSweets', 'Chocolates & Sweets'), ('PersonalCare', 'Personal Care & Hygiene'), ('CleaningHousehold', 'Cleaning & Household Essentials'), ('BabyCare', 'Baby Care & Nutrition'), ('PetCare', 'Pet Care Products')], max_length=50)),
                ('description', models.TextField()),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('first_product_image', models.ImageField(upload_to='ProductImg/')),
                ('second_product_image', models.ImageField(blank=True, null=True, upload_to='ProductImg/')),
                ('third_product_image', models.ImageField(blank=True, null=True, upload_to='ProductImg/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.FloatField()),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
