# Generated by Django 4.2.19 on 2025-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Fresh Vegetables'), ('Fruits', 'Fresh Fruits'), ('DairyBakery', 'Dairy & Bakery Products'), ('Proteins', 'Proteins (Eggs, Meat, Fish, Plant-based)'), ('Beverages', 'Beverages (Tea, Coffee, Juices, Soft Drinks, Hard Drinks)'), ('PicklesJams', 'Pickles, Jams & Spreads'), ('InstantFoods', 'Instant & Ready-to-Eat Foods'), ('FrozenFoods', 'Frozen Foods & Ready-to-Cook'), ('SnacksNamkeen', 'Snacks, Namkeen & Chips')], max_length=50),
        ),
    ]
