# Generated by Django 4.2.19 on 2025-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Fresh Vegetables'), ('Fruits', 'Fresh Fruits'), ('DairyBakery', 'Dairy & Bakery Products'), ('Proteins', 'Proteins (Eggs, Meat, Fish, Plant-based)'), ('Beverages', 'Beverages (Tea, Coffee, Juices, Soft Drinks, Hard Drinks)'), ('PicklesJams', 'Pickles, Jams & Spreads'), ('InstantFoods', 'Instant & Ready-to-Eat Foods'), ('Grocery', 'Staples (rice,lentil,flour,grains) Frozen Foods & Ready-to-Cook'), ('Banner', 'Banner'), ('OffSeasonal', 'OffSeasonal'), ('OnSeasonal', 'OnSeasonal')], max_length=50),
        ),
    ]
