# Generated by Django 4.2.19 on 2025-03-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='total_price',
        ),
    ]
