# Generated by Django 4.2.19 on 2025-03-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_remove_customer_country_remove_customer_country_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
